CREATE TABLE IF NOT EXISTS Stock(
    ID INT PRIMARY KEY,
    Name VARCHAR(50),
    Quantity INT,
    Price INT
);

DROP TABLE IF EXISTS Login;

CREATE TABLE Login(
    UniqueID INT PRIMARY KEY AUTO_INCREMENT,
    UserName VARCHAR(50) UNIQUE NOT NULL,
    SaltedPassword VARCHAR(255),
    Role VARCHAR(20) DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);