CREATE TABLE IF NOT EXISTS Stock(
    ID INT PRIMARY KEY,
    Name VARCHAR(50),
    Quantity INT,
    Price INT
);

DROP TABLE IF EXISTS Login;

CREATE TABLE "Login"(
    UniqueID int generated by default as identity primary key,
    FullName varchar(50) not null,
    UserName VARCHAR(50) NOT NULL,
    SaltedPassword VARCHAR(255),
    Role VARCHAR(20) DEFAULT 'user',
    phone_number text not null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);